### ISSUE TITLE
Add Modo Multiplayer e Single Player

### ISSUE THREAD

**Issue by AlexandreSLangunno** [oprogramadorreal/Prong.py#3]
Olá De novo 
Com base na teoria do seu video do Prong do C# tive uma ideia de fazer o "Modo Multiplayer e Single Player" do seu jogo 
hehe
Fiz o Jogador 2 ficar mexendo de um lado para o outro 
Se quiser vou fazer um Pull Request
Obrigado pela Paciencia e a Atenção =)

**Comment by oprogramadorreal** [comment]
Hahah que legal, cara!! Faz pull request sim! Acho que é bem valioso! Outras pessoas podem aprender lendo seu código. Muito obrigado de novo!
